Add risk
PreventRippingOffApp/Server pull request #16
Opened 2019-12-23 14:03 UTC by tohutohu

/riskエンドポイントを作成しました
現状危険度判定が存在しないので、近隣1kmの報告数を危険度として返すようにしています。

2019-12-23 15:26 UTC, who3411 requested changes
2つほどコメントしました。
そこさえ直していただければ問題ないと思います。

2019-12-23 15:26 UTC, who3411 commented on app.py
> +        check_location(location, result)
これは私の作り方が悪かった(後でミスに気づいてcheck_locationを修正せずに修正した)ので本当に申し訳ないのですが、mongodbの2d locationは[lng, lat]形式になっているので、check_locationの後ろに
`location = [location[1], location[0]]`
などして[lng, lat]の形式にしないと値によってはエラーが発生します。

2019-12-23 15:26 UTC, who3411 commented on app.py
> +        '$near': {'$geometry': {'type':'Point', 'coordinates': [5, 5]}}
[5,5]が現在地の位置情報に該当するので、
`'coodinates': location`
でお願いします。

2019-12-24 10:10 UTC, tohutohu commented
修正しました

2019-12-27 04:04 UTC, who3411 commented
確認遅れてしまい大変申し訳ありません。実際に動かしてみて、いくつか別の問題があったので修正した物を用意しました。前回気付かず申し訳ありませんでした。
確認のほど、よろしくお願いいたします。

- `def send_location()` のままであったため `def risk()` に変更
- 現在地から距離が近い順に並べる`$near` 演算子が使用されていたため、1km以内の現在地を取得する `$geoWithin` の `$centerSphere` 演算子に変更
- 161行目のinvalid syntaxを修正

問題なさそうであれば、このままマージしていただいて構いません。

2019-12-30 14:03 UTC, merged